sudo: true
language: node_js
node_js:
  - 12
  - 10
services:
  - postgresql
addons:
  postgresql: "10"
  apt: 
    - postgresql-10
    - postgresql-client-10
env:
  - SERVER_PORT=8080 DB_NAME=artscenter DB_USERNAME=testuser DB_PASSWORD=testuser
cache:
  directories:
    - node_modules
before_script:
  - sudo psql -c 'create database artscenter;' -U postgres
  - sudo psql -c "CREATE USER testuser WITH PASSWORD 'testuser';" -U postgres
  - sudo psql -c "ALTER USER testuser WITH SUPERUSER;" -U postgres
script:
  - npm run build
  - npm run test