sudo: false
language: node_js
node_js:
  - "8"
  - "9"
  - "10"
services:
  - postgresql
cache:
  directories:
    - node_modules
before_script:
  - psql -c 'create database artscenter;' -U postgres
script:
  - npm run build
  - npm run test