sudo: false
language: node_js
node_js:
  - 12
  - 10
services:
  - postgresql
addons:
  postgresql: "10"
  apt: 
    - postgresql-10
    - postgresql-client-10
env:
  - SERVER_PORT=8080 DB_NAME=artscenter DB_USERNAME=postgres DB_PASSWORD=''
cache:
  directories:
    - node_modules
before_script:
  - postgres -V
  - psql -c 'create database artscenter;' -U postgres
  - psql -c "CREATE USER testuser WITH PASSWORD 'testuser';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE artscenter TO testuser;" -U postgres
script:
  - npm run build
  - npm run test